server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8 #&useSSL=false&serverTimezone=UTC
    username: root
    password: root123456
  # 配置国际化校验,在消息头中指定 locale： zh_CH / en_US
  messages:
    basename: messages/validation
  # 配置连接redis的参数
  redis:
    ssl: false
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 1000
    #    password: root
    lettuce: # 是一个高性能基于java编写的redis驱动架构
      pool:
        max-active: 100
        max-wait: -1
        min-idle: 0
        max-idle: 20

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.hello.springboothello.dao.mybatis
  configuration:
    map-underscore-to-camel-case: true # https://blog.csdn.net/weixin_43287239/article/details/98867722

pagehelper:
  # 标识是数据库方言
  helper-dialect: mysql
  # 启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages 会查询最后一页
  reasonable: true
  # 支持通过Mapper接口参数来传递分页参数，默认为flase，分页插件会从查询方法的参数值中，
  #   自动根据上面params配置的字段中取值，查找到合适的值时就会自动分页
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值，
  #   可以配置pageNum，pageSize，count，pageSizeZero，reasonable，
  #   不配置映射的用默认值，默认值为pageNum=pageNum，pageSize=pageSize，count=countSql
  #   ，reasonable=reasonable，pageSizeZero=pageSizeZero
  params: count=countSql
  # 如果pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
  page-size-zero: true


# 通过yml配置文件配置日志
#logging:
#  level:
#    root: info
#    com:
#      hello:
#        springboothello: WARN


