server:
  port: 8090

spring:
  datasource:
    # 驱动
    driver-class-name: org.h2.Driver
    # h2 内存数据库 内存模式连接配置 库名：myh2
    url: jdbc:h2:mem:myh2
    # 初始化数据表 DDl
    schema: classpath:sql/schema.sql
    # 初始化数据 DML
    data: classpath:sql/data.sql
    platform: h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # 配置国际化校验,在消息头中指定 locale： zh_CH / en_US
  messages:
    basename: messages/validation
  # 配置连接redis的参数
  redis:
    ssl: false
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 1000
#    password: root
    lettuce: # 是一个高性能基于java编写的redis驱动架构
      pool:
        max-active: 100
        max-wait: -1
        min-idle: 0
        max-idle: 20



# 通过yml配置文件配置日志
#logging:
#  level:
#    root: info
#    com:
#      hello:
#        springboothello: WARN


